name: MY CI/CD Pipeline

on:
  push:
    branches:
      - main  # Runs when code is pushed to main
      - feature/AmazingFeature  # Runs when code is pushed to feature branch

  pull_request:
    branches:
      - main  # Runs when a pull request is made to main

jobs:
  test:
    name: Run Tests
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Set Up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.12'

      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run Tests
        run: pytest --maxfail=1 --disable-warnings --exitfirst || exit 1

  deploy:
    name: Deploy to EC2
    needs: test
    runs-on: ubuntu-latest
    steps:
      - name: Determine Branch
        id: branch_name
        run: echo "branch=${GITHUB_REF#refs/heads/}" >> $GITHUB_ENV

      - name: SSH and Deploy
        uses: appleboy/ssh-action@v0.1.6
        with:
          host: ${{ secrets.EC2_IP }}
          username: ubuntu
          key: ${{ secrets.EC2_SSH_KEY }}
          script: |
            cd /var/www/fastapi-book-project
            git checkout ${{ env.branch }}  # Checkout the correct branch
            git pull origin ${{ env.branch }}  # Get the latest changes
            
            source .venv/bin/activate  # Activate virtual environment
            pip install -r requirements.txt  # Install dependencies
            
            sudo systemctl daemon-reload  # Reload systemd if needed
            sudo systemctl restart fastapi-app  # Restart the FastAPI service
            sudo systemctl enable fastapi-app  # Ensure it starts on boot
